version: '3'
services:
  nginx:
    container_name: nginx
    build: ./infra/nginx/
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    container_name: php
    build: ./infra/php/
    volumes:
      - ./html:/var/www/html